### ISSUE TITLE
System - Draft Milestone 4 Document - Documentation

### ISSUE THREAD

**Issue by tatkg24** [JoheeYeom0103/TicktHub#50]
- [ ] **An update of your testing implementation so far:**
- describe all the approaches you have done to test your project. 
- describe what else you will be doing to improve the testing in the future weeks
- [ ] **An update of the functionality that has been tested so far**,
- What's working, what's passing, what's not?
 - [ ] **What automation have you implemented in your project so far? How is it working?** 
 - [ ] **A summary of the project so far:**
 - Where you are in the project?
 - Reflect on how it is functioning.
 - Add some comments on:
           1. The process  
           2. How is the process you selected as a team working?  
           3. Does anything need to change?
